Fix No Test Handle

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -30,14 +30,19 @@ jobs:
         run: flutter pub get
 
       - name: Run Unit Tests
-        run: flutter test || {
+        run: |
+          set +e
+          flutter test
           status=$?
+          set -e
+
           if [ $status -eq 79 ]; then
-          echo "⚠️ No unit tests found. Continuing build..."
-          exit 0
+            echo "⚠️ No unit tests found. Continuing build..."
+            exit 0
+          elif [ $status -ne 0 ]; then
+            echo "❌ Tests failed with exit code $status"
+            exit $status
           fi
-          exit $status
-          }
 
       - name: Build iOS App (Validation)
         run: flutter build ios --no-codesign --debug
